EXP_NAME="w8a8_ours"

CFG="./t2v/configs/quant/opensora/16x512x512.py"  # the opensora config
Q_CFG="./t2v/configs/quant/opensora/$EXP_NAME.yaml"  # the config of calibration
CKPT_PATH="./logs/split_ckpt/OpenSora-v1-HQ-16x512x512-split.pth"  # splited ckpt generated by split_ckpt.py
CALIB_DATA_DIR="./logs_100steps/calib_data"  # your path of calib data
OUTDIR="./logs_100steps/$EXP_NAME"  # your path to save the calibration result
GPU_ID=$1

# calibration (w8a8: no mixed-precision yaml needed)
CUDA_VISIBLE_DEVICES=$GPU_ID python t2v/scripts/calib.py $CFG --ckpt_path $CKPT_PATH --calib_config $Q_CFG --outdir $OUTDIR \
    --calib_data $CALIB_DATA_DIR/calib_data.pt \
    --part_fp \
    --precompute_text_embeds ./t2v/utils_files/text_embeds.pth \
